### PR TITLE
Feature | DarkMode added to website

### PR DESCRIPTION
**Pull request by sambitsingha**
I have created the dark mode toggler in the website using tailwind css features. 

1) The button in the navbar acts as the toggler. 
2) The dark mode background has a deep blue gradient. 

# Closes issue #23 
## I am open to reviews

### CODE REVIEW

**Comment by sambitsingha** [comment]
@RamitVishwakarma New PR given. Converted css files to tailwind css classes wherever applicable.

**Comment by RamitVishwakarma** [comment]
I wanted the dark mode to be done inside a custom hook
Your approach will make the code way too verbose
heres a sample how a custom hook can be used
Screenshot 2024-05-12 200231
no need to create a useLocalStorage hook just store the theme in either local or sessionStorage
Create a darkModeSwitcher where u can update the value in local storage
Make sure to pull changes before u work on this

**Comment by sambitsingha** [comment]
@RamitVishwakarma I used tailwind darkMode classes , which is more easy than these

you just need to add  ``dark:( your css class)`` and that's all

**Comment by RamitVishwakarma** [comment]
> @RamitVishwakarma I used tailwind darkMode classes , which is more easy than these
> 
> you just need to add `dark:( your css class)` and that's all

No I was talking about your handling of dark mode you have only done it in landing page and your approach requires handling the dark mode toggle in every single page which makes the code verbose with a custom hook you only have to handle it in a single place and it does the work even if you go to other pages for example look at this
image

**Comment by sambitsingha** [comment]
@RamitVishwakarma Oh yes I have done it landing page only. Yes I can keep the toggler in navbar and apply dark mode to the whole website , just by using the tailwind classes. 

If you want , I will continue with it

**Pull request closed without merging**
