### PR TITLE
FIX  : UI issue #4

### PR DESCRIPTION
**Pull request by Debanjannnn**
#4 Fixed the Landing , login ,Searchbar ,herosection and footer part of the code with Tailwind

### CODE REVIEW

**Comment by Debanjannnn** [comment]
> Fixed the Landing , login ,Searchbar ,herosection and footer part of the code with Tailwind

**Comment by Debanjannnn** [comment]
> #4 Fixed the Landing , login ,Searchbar ,herosection and footer part of the code with Tailwind

please review  the PR @RamitVishwakarma

**Comment by RamitVishwakarma** [comment]
@Debanjannnn  hello debanjan can you pull the changes and fix the conflict thats been there in navbar.jsx

**Comment by Debanjannnn** [comment]
Sure

**Comment by Debanjannnn** [comment]
@RamitVishwakarma   Did the change, please check the PR  #37 
Screenshot 2024-05-12 123241
Screenshot 2024-05-12 123213
Screenshot 2024-05-12 123145

**Comment by Debanjannnn** [comment]
image

**Pull request merged**
